### ISSUE TITLE
error: 'Base64' was not declared in this scope for ESP8266

### ISSUE THREAD

**Issue by mistergreen** [agdl/Base64#2]
I've been using this lib and it works fine for the Arduino. I'm compiling for the esp8266
I'm running your example and this is the error

> Base64Encode:32: error: 'Base64' was not declared in this scope
   int encodedLength = Base64.encodedLength(inputStringLength);

Not sure what why the extern doesn't work.

**Comment by uvwxy** [comment]
I had the same issue, and "solved" it by using the provided library with the ESP8266:

```
#include <base64.h>

...

"Authorization: Basic " + base64::encode("user:pass") + "\r\n" +

```

Still would like to understand why the Base64.h is not getting picked up.

**Comment by mcr-ksh** [comment]
+1. same here.

**Comment by agdl** [comment]
Yes you should use the built-in encoding with ESP8266
